import assert from "node:assert/strict";
import test from "node:test";
import { auditContext, auditV3, emitAudit, validateAuditEventV3 } from "../src/remote/audit.js";
const env={DEPLOY_ENVIRONMENT:"sandbox",AUDIT_HMAC_EPOCH:"2026-Q3",VERSION_METADATA:{id:"version-1",tag:"tag-1",timestamp:"2026-07-21T12:00:00.000Z"}};
function event(){return auditV3(auditContext(env,"pipedrive-mcp-sandbox"),{ts:"2026-07-21T12:00:00.000Z",category:"route",requestId:"request-1",actorId:"anonymous",route:"/mcp",operation:"route.outcome",effect:"read",outcome:"success",httpStatus:200,latencyMs:0});}
test("native v3 binds real deployment and version context",()=>{const value=event();assert.equal(value.worker,"pipedrive-mcp-sandbox");assert.equal(value.versionId,"version-1");});
test("strict contract table rejects unsafe shapes",()=>{const good=event() as any;const targets=Object.fromEntries(Array.from({length:13},(_,i)=>[`item${i}_id`,i]));for(const mutate of [(x:any)=>x.ts="2026-02-30T12:00:00.000Z",(x:any)=>delete x.route,(x:any)=>x.route="bad route",(x:any)=>x.eventId="bad",(x:any)=>x.targetIds=targets,(x:any)=>x.targetIds={bad:"x"},(x:any)=>x.measurements={unknown:-1},(x:any)=>x.policyChanges={writes:{from:true}},(x:any)=>x.providerStatus=429,(x:any)=>x.previousActorId="a".repeat(32),(x:any)=>x.extra=true,(x:any)=>x.route="/"+"é".repeat(3000)]){const value=structuredClone(good);mutate(value);assert.throws(()=>validateAuditEventV3(value));}validateAuditEventV3(good);});
test("unknown context emits one redacted config diagnostic",async()=>{const seen:any[]=[];await emitAudit({write:async x=>{seen.push(x);}} as any,auditContext({DEPLOY_ENVIRONMENT:"bad"},"unknown"),{ts:"2026-07-21T12:00:00.000Z",category:"route",requestId:"request-1",actorId:"anonymous",route:"/mcp",operation:"route.outcome",effect:"read",outcome:"success",httpStatus:200,latencyMs:0});assert.equal(seen.length,1);assert.equal(seen[0].category,"config");});
test("complete optional v3 fields and provider variants validate",()=>{const value={...event(),dryRun:true,targetIds:{deal_id:1},tenantId:"tenant-1",errorCode:"access_token_missing",policyRevision:1,policyChanges:{writes:{from:false,to:true}},measurements:{cpu_ms:1},previousActorId:"a".repeat(32),previousAuditEpoch:"2026-Q2"};validateAuditEventV3(value);validateAuditEventV3({...event(),providerClass:"timeout",attempt:1});validateAuditEventV3({...event(),providerClass:"transport",attempt:1});validateAuditEventV3({...event(),providerClass:"429",providerStatus:429,attempt:1});});
