import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { readAuditNdjson, queryAudit } from "../scripts/lib/audit-operations.mjs";
test("local audit parser ignores platform records and queries only marked records", async () => {
  const parsed = await readAuditNdjson("tests/fixtures/audit/marked.ndjson");
  assert.equal(parsed.invalid, 0); assert.equal(parsed.records.length, 1); assert.equal(queryAudit(parsed.records, { operation: "audit.export.heartbeat" }).length, 1);
});
test("offline parser rejects marked unsafe v3 mutations", async()=>{const base=JSON.parse(readFileSync("tests/fixtures/audit/marked.ndjson","utf8"));const root=mkdtempSync(join(tmpdir(),"audit-"));try{for(const mutate of [(x:any)=>x.ts="2026-02-30T12:00:00.000Z",(x:any)=>delete x.route,(x:any)=>x.route="bad route",(x:any)=>x.eventId="bad",(x:any)=>x.targetIds=Object.fromEntries(Array.from({length:13},(_,i)=>[`item${i}_id`,i])),(x:any)=>x.targetIds={bad:"x"},(x:any)=>x.measurements={unknown:-1},(x:any)=>x.policyChanges={writes:{from:true}},(x:any)=>x.providerStatus=429,(x:any)=>x.attempt=0,(x:any)=>x.previousActorId="a".repeat(32),(x:any)=>x.extra=true,(x:any)=>x.environment="unknown",(x:any)=>x.route="/"+"é".repeat(3000)]){const value=structuredClone(base);mutate(value);const path=join(root,"record.ndjson");writeFileSync(path,JSON.stringify(value)+"\n");const parsed=await readAuditNdjson(path);assert.equal(parsed.invalid,1);assert.equal(parsed.records.length,0);}}finally{rmSync(root,{recursive:true,force:true});}});
test("reader limits and gzip failures are deterministic",async()=>{const root=mkdtempSync(join(tmpdir(),"audit-"));try{const plain=join(root,"a.ndjson"),gzip=join(root,"a.ndjson.gz"),bad=join(root,"bad.gz");writeFileSync(plain,"{\"platform\":true}\n");await assert.rejects(()=>readAuditNdjson(plain,{input:1}),/compressed/);writeFileSync(gzip,gzipSync("x".repeat(100)));await assert.rejects(()=>readAuditNdjson(gzip,{decompressed:10}),/decompressed/);writeFileSync(bad,"not-gzip");await assert.rejects(()=>readAuditNdjson(bad),/incorrect header/);}finally{rmSync(root,{recursive:true,force:true});}});
test("record aggregate output and filter limits are injectable",async()=>{const root=mkdtempSync(join(tmpdir(),"audit-"));try{const valid=readFileSync("tests/fixtures/audit/marked.ndjson","utf8"),path=join(root,"x.ndjson");writeFileSync(path,valid+valid);await assert.rejects(()=>readAuditNdjson(path,{records:1}),/record_limit/);await assert.rejects(()=>readAuditNdjson(path,{aggregate:1}),/aggregate/);const records=(await readAuditNdjson(path)).records;assert.throws(()=>queryAudit(records,{},1),/output/);for(const filter of [{bad:"x"},{outcome:"bad"},{from:"2026-02-30T12:00:00.000Z"},{to:3 as any}])assert.throws(()=>queryAudit(records,filter));}finally{rmSync(root,{recursive:true,force:true});}});
test("offline accepts complete optional event",async()=>{const root=mkdtempSync(join(tmpdir(),"audit-"));try{const value=JSON.parse(readFileSync("tests/fixtures/audit/marked.ndjson","utf8"));Object.assign(value,{dryRun:true,targetIds:{deal_id:1},tenantId:"tenant-1",errorCode:"access_token_missing",policyRevision:1,policyChanges:{writes:{from:false,to:true}},measurements:{cpu_ms:1},previousActorId:"a".repeat(32),previousAuditEpoch:"2026-Q2"});const path=join(root,"optional.ndjson");writeFileSync(path,JSON.stringify(value)+"\n");const parsed=await readAuditNdjson(path);assert.equal(parsed.records.length,1);assert.equal(queryAudit(parsed.records,{tenantId:"tenant-1"}).length,1);}finally{rmSync(root,{recursive:true,force:true});}});
test("platform v is ignored and complete legacy records are queryable",async()=>{const root=mkdtempSync(join(tmpdir(),"audit-"));try{const base={ts:"2026-07-21T12:00:00.000Z",requestId:"request-1",actorId:"anonymous",route:"/mcp",operation:"read",effect:"read",outcome:"success",httpStatus:200,latencyMs:0};const path=join(root,"legacy.ndjson");writeFileSync(path,[JSON.stringify({v:99,platform:true}),"not json v=2",JSON.stringify({...base,v:1}),JSON.stringify({...base,v:2,auditEpoch:"2026-Q3"})].join("\n"));const parsed=await readAuditNdjson(path);assert.equal(parsed.ignored,2);assert.equal(parsed.legacyRecords,2);assert.equal(queryAudit(parsed.records,{operation:"read"}).length,2);}finally{rmSync(root,{recursive:true,force:true});}});
test("offline permits only config unknown context and validates optional scalars",async()=>{const root=mkdtempSync(join(tmpdir(),"audit-"));try{const base=JSON.parse(readFileSync("tests/fixtures/audit/marked.ndjson","utf8")),path=join(root,"config.ndjson");const config={...base,category:"config",environment:"unknown",worker:"unknown",versionId:"unknown",versionTag:"unknown",uploadedOn:"unknown",auditEpoch:"unknown"};writeFileSync(path,JSON.stringify(config));assert.equal((await readAuditNdjson(path)).records.length,1);for(const mutate of [(x:any)=>x.dryRun="yes",(x:any)=>x.tenantId="bad value",(x:any)=>x.errorCode="bad value",(x:any)=>x.policyRevision=-1]){const value=structuredClone(base);mutate(value);writeFileSync(path,JSON.stringify(value));assert.equal((await readAuditNdjson(path)).invalid,1);}}finally{rmSync(root,{recursive:true,force:true});}});
test("line cap and tolerant v3 marker boundaries",async()=>{const root=mkdtempSync(join(tmpdir(),"audit-"));try{const path=join(root,"line.ndjson");writeFileSync(path,'{ "recordType" : "pipedrive.audit", "x":"'+"x".repeat(100));let result=await readAuditNdjson(path,{line:20});assert.equal(result.invalid,1);writeFileSync(path,'{"platform":"'+"x".repeat(100));result=await readAuditNdjson(path,{line:20});assert.equal(result.ignored,1);writeFileSync(path,'{ "x": 1, "recordType" : "pipedrive.audit"');result=await readAuditNdjson(path);assert.equal(result.invalid,1);writeFileSync(path,'{ "platform": ');result=await readAuditNdjson(path);assert.equal(result.ignored,1);}finally{rmSync(root,{recursive:true,force:true});}});
