import { escapeHtml, renderPageShell } from "./pageShell.js";
import type { AdminConnectionProjection, TenantAdminAction, TenantAdminProjection } from "./tenantRegistry.js";

export type AdminNotice = "approve" | "suspend" | "resume" | "force-disconnected";
export type ForceDisconnectDisplayTarget = Pick<AdminConnectionProjection, "connectionRef" | "accessEmail" | "domain" | "state" | "connectedAtMs" | "lastUsedAtMs">;
export type PipedriveAdminPageInput = { projection: TenantAdminProjection; nonce: string; notice?: AdminNotice; error?: "ticket" | "registry" | "conflict" };
const notices: Record<AdminNotice, string> = { approve: "Le domaine est approuvé. Il permet maintenant un OAuth individuel, sans ajouter d’utilisateur Access ni de connexion.", suspend: "Le domaine est suspendu. Les nouveaux OAuth, callbacks, rafraîchissements et appels MCP sont bloqués, sans supprimer les jetons locaux ni l’autorisation fournisseur. Le délai d’inactivité de 90 jours continue.", resume: "Le domaine est à nouveau éligible. Cette reprise ne restaure aucune connexion ni aucun jeton expiré.", "force-disconnected": "La connexion locale de cet utilisateur a été supprimée." };

export function renderPipedriveAdminPage(input: PipedriveAdminPageInput): string {
  const notice = input.error ? `<p class="notice error" role="alert">${input.error === "ticket" ? "La confirmation a expiré, a déjà été utilisée ou ne correspond plus à l’état enregistré." : input.error === "conflict" ? "L’état a changé. Rechargez la projection avant de recommencer." : "Le registre sécurisé est momentanément indisponible."}</p>` : input.notice ? `<p class="notice success" role="status">${notices[input.notice]}</p>` : "";
  const tenants = [...input.projection.tenants].sort((a, b) => a.domain.localeCompare(b.domain)).map((tenant) => `<tr><td>${escapeHtml(tenant.domain)}.pipedrive.com</td><td>${tenant.status === "active" ? "Actif" : "Suspendu"}</td><td>${escapeHtml(tenant.companyName ?? "À vérifier au premier OAuth")}</td><td>${escapeHtml(tenant.companyId ?? "—")}</td><td>${dateCell(tenant.updatedAtMs)}</td><td>${tenant.connectedUserCount}</td><td><form method="post" action="/admin/pipedrive/action/confirm"><input type="hidden" name="action" value="${tenant.status === "active" ? "suspend" : "resume"}"><input type="hidden" name="domain" value="${escapeHtml(tenant.domain)}"><button${tenant.status === "active" ? ' class="button-danger"' : ""} type="submit">${tenant.status === "active" ? "Suspendre" : "Reprendre"}</button></form></td></tr>`).join("") || '<tr><td colspan="7">Aucun domaine Pipedrive approuvé.</td></tr>';
  const connections = [...input.projection.connections].sort((a, b) => a.domain.localeCompare(b.domain) || a.accessEmail.localeCompare(b.accessEmail)).map(connectionRow).join("") || '<tr><td colspan="7">Aucune connexion utilisateur indexée.</td></tr>';
  return renderPageShell({ title: "Administration Pipedrive · MCP", nonce: input.nonce, width: "admin", children: `<header><p class="eyebrow">Pipedrive MCP · administrateur</p><h1>Admission et connexions</h1><p class="intro">Cette autorité gère l’éligibilité globale. Elle ne donne accès à aucun jeton ni à aucune identité Pipedrive d’utilisateur.</p></header>${notice}${rotationReceipt(input.projection)}<section aria-labelledby="approve-title"><h2 id="approve-title">Approuver un domaine</h2><p>Cette approbation permet un OAuth individuel. Elle n’ajoute aucun utilisateur Access ni aucune connexion.</p><form method="post" action="/admin/pipedrive/approve/confirm"><label for="domain">Sous-domaine Pipedrive</label><input id="domain" name="domain" type="text" maxlength="63" required><button type="submit">Préparer l’approbation</button></form></section><section aria-labelledby="tenants-title"><h2 id="tenants-title">Domaines approuvés</h2><div class="table-region" tabindex="0" aria-label="Tableau des domaines approuvés"><table><caption>Registre d’admission, trié par domaine.</caption><thead><tr><th scope="col">Domaine</th><th scope="col">État</th><th scope="col">Société</th><th scope="col">ID société</th><th scope="col">Mis à jour</th><th scope="col">Connexions</th><th scope="col">Action</th></tr></thead><tbody>${tenants}</tbody></table></div></section><section aria-labelledby="connections-title"><h2 id="connections-title">Connexions utilisateur</h2><div class="table-region" tabindex="0" aria-label="Tableau des connexions utilisateur"><table><caption>Projection opérationnelle, triée par domaine puis e-mail Access.</caption><thead><tr><th scope="col">E-mail Access</th><th scope="col">Domaine</th><th scope="col">État</th><th scope="col">Connexion</th><th scope="col">Dernier usage</th><th scope="col">Expiration du jeton</th><th scope="col">Action</th></tr></thead><tbody>${connections}</tbody></table></div></section>` });
}

function rotationReceipt(projection: TenantAdminProjection): string {
  const receipt = projection.encryptionReceipt ?? { generatedAtMs: 0, currentKeyStates: { primary: 0, old: 0, legacy: 0, unknown: projection.connections.length } };
  const counts = receipt.currentKeyStates;
  const blocked = counts.old + counts.legacy + counts.unknown > 0;
  const evidence = blocked ? "La retraite de clé est bloquée : des enveloppes anciennes, legacy ou inconnues restent indexées." : "Aucune enveloppe active ancienne, legacy ou inconnue n’est indexée.";
  const latest = receipt.latestNonPrimaryUse ? `Dernière utilisation non primaire observée : ${escapeHtml(receipt.latestNonPrimaryUse.source)} · ${dateCell(receipt.latestNonPrimaryUse.atMs)}. Attendre 30 jours après cette date avant la retraite planifiée.` : "Aucune utilisation non primaire horodatée n’est disponible ; ne concluez pas à zéro utilisation historique.";
  return `<section aria-labelledby="rotation-title"><h2 id="rotation-title">Preuve de rotation des clés</h2><p role="status">${evidence}</p><dl><dt>Primaire</dt><dd>${counts.primary}</dd><dt>Ancienne</dt><dd>${counts.old}</dd><dt>Legacy</dt><dd>${counts.legacy}</dd><dt>Inconnue</dt><dd>${counts.unknown}</dd><dt>Projection générée</dt><dd>${dateCell(receipt.generatedAtMs)}</dd></dl><p>${latest}</p></section>`;
}

export function renderApproveConfirmation(input: { domain: string; actionToken: string; nonce: string }): string { return confirmationShell(input.nonce, "Confirmer l’approbation", `${escapeHtml(input.domain)}.pipedrive.com`, "Cette approbation permet un OAuth individuel. Elle n’ajoute aucun utilisateur Access ni aucune connexion.", "/admin/pipedrive/tenant", `<input type="hidden" name="action" value="approve"><input type="hidden" name="domain" value="${escapeHtml(input.domain)}"><input type="hidden" name="csrf" value="${escapeHtml(input.actionToken)}">`, "Confirmer l’approbation"); }
export function renderAdminActionConfirmation(input: { action: Exclude<TenantAdminAction, "approve">; target: string; actionToken: string; nonce: string; forceTarget?: ForceDisconnectDisplayTarget }): string {
  if (input.action === "force-disconnect") { if (!input.forceTarget) throw new Error("force_disconnect_target_missing"); const t = input.forceTarget; return confirmationShell(input.nonce, "Forcer la déconnexion", `${escapeHtml(t.accessEmail)} · ${escapeHtml(t.domain)}.pipedrive.com · ${stateLabel(t.state)} · ${dateCell(t.connectedAtMs)}`, "Supprime les jetons OAuth conservés par le Worker pour cette connexion, sans modifier Access ni l’autorisation fournisseur.", "/admin/pipedrive/force-disconnect", `<input type="hidden" name="connection_ref" value="${escapeHtml(t.connectionRef)}"><input type="hidden" name="csrf" value="${escapeHtml(input.actionToken)}">`, "Forcer la déconnexion"); }
  const suspend = input.action === "suspend"; return confirmationShell(input.nonce, suspend ? "Suspendre le domaine" : "Reprendre le domaine", `${escapeHtml(input.target)}.pipedrive.com`, suspend ? "Bloque les nouveaux OAuth, callbacks, rafraîchissements et MCP. Les jetons locaux et l’autorisation fournisseur sont conservés, et le délai d’inactivité de 90 jours continue." : "Restaure seulement l’éligibilité.", "/admin/pipedrive/tenant", `<input type="hidden" name="action" value="${input.action}"><input type="hidden" name="domain" value="${escapeHtml(input.target)}"><input type="hidden" name="csrf" value="${escapeHtml(input.actionToken)}">`, suspend ? "Suspendre le domaine" : "Reprendre le domaine");
}
function confirmationShell(nonce: string, title: string, target: string, consequence: string, action: string, hidden: string, verb: string): string { return renderPageShell({ title, nonce, width: "admin", children: `<header><p class="eyebrow">Confirmation requise</p><h1>${title}</h1></header><section class="panel"><h2>Cible</h2><p>${target}</p><h2>Conséquence</h2><p>${consequence}</p><form method="post" action="${action}">${hidden}<label class="checkbox-row"><input type="checkbox" name="confirm" value="yes" required>Je comprends cette conséquence et je confirme l’action.</label><div class="actions"><button class="${verb.startsWith("Suspendre") || verb.startsWith("Forcer") ? "button-danger" : ""}" type="submit">${verb}</button><a href="/admin/pipedrive">Annuler</a></div></form></section>` }); }
function connectionRow(c: AdminConnectionProjection): string { return `<tr><td>${escapeHtml(c.accessEmail)}</td><td>${escapeHtml(c.domain)}.pipedrive.com</td><td>${stateLabel(c.state)}</td><td>${dateCell(c.connectedAtMs)}</td><td>${dateCell(c.lastUsedAtMs)}</td><td>${dateCell(c.tokenExpiresAtMs)}</td><td><form method="post" action="/admin/pipedrive/action/confirm"><input type="hidden" name="action" value="force-disconnect"><input type="hidden" name="connection_ref" value="${escapeHtml(c.connectionRef)}"><button class="button-danger" type="submit" aria-label="Forcer la déconnexion de ${escapeHtml(c.accessEmail)}">Forcer la déconnexion</button></form></td></tr>`; }
function stateLabel(state: string): string { return state === "connected" ? "Connectée" : "Reconnexion requise"; }
function dateCell(value: number | undefined): string { if (value === undefined || !Number.isFinite(value)) return "—"; const date = new Date(value); return `<time datetime="${date.toISOString()}">${new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(date)}</time>`; }
