import { escapeHtml, renderPageShell } from "./pageShell.js";
import type { UserPolicyRecord } from "./policy.js";

export type SettingsPageInput = { email: string; policy: UserPolicyRecord; csrf: string; nonce: string; saved: boolean; error?: string; company?: string; domain?: string };
export function renderSettingsPage(input: SettingsPageInput): string {
  const status = input.saved ? '<p class="notice success" role="status">Vos permissions ont été enregistrées.</p>' : input.error ? `<p class="notice error" role="alert">${escapeHtml(input.error)}</p>` : "";
  const context = input.domain ? `${escapeHtml(input.company ?? "Société vérifiée")} · ${escapeHtml(input.domain)}.pipedrive.com` : "Votre connexion Pipedrive vérifiée";
  return renderPageShell({ title: "Permissions Pipedrive · MCP", nonce: input.nonce, children: `<nav aria-label="Navigation"><a href="/pipedrive">Connexion</a><a href="/settings" aria-current="page">Permissions</a></nav><header><p class="eyebrow">Pipedrive MCP</p><h1>Permissions de votre connexion</h1><p class="intro">${context}. Identité Access : ${escapeHtml(input.email)}.</p></header>${status}<section aria-labelledby="capabilities-title"><h2 id="capabilities-title">Capacités</h2><p class="muted">La lecture CRM reste disponible. Toute nouvelle société commence en lecture seule. Les écritures réelles exigent explicitement <code>dry_run=false</code>, la valeur par défaut est <code>dry_run=true</code>.</p><form method="post" action="/settings"><input type="hidden" name="csrf" value="${escapeHtml(input.csrf)}"><input type="hidden" name="revision" value="${input.policy.revision}"><fieldset><legend>Autorité optionnelle</legend><div class="checks"><label class="checkbox-row"><input type="checkbox" name="writes" value="yes"${input.policy.writes ? " checked" : ""}>Écritures CRM. Créer ou modifier des données.</label><label class="checkbox-row"><input type="checkbox" name="mailbox" value="yes"${input.policy.mailbox ? " checked" : ""}>Lecture Mailbox. Lire les fils et messages Pipedrive. Seule la liaison d’un fil exige aussi les écritures CRM.</label><label class="checkbox-row"><input type="checkbox" name="deletes" value="yes"${input.policy.deletes ? " checked" : ""}>Suppressions. Disponible seulement avec les écritures CRM.</label></div></fieldset><p class="panel"><label class="checkbox-row"><input type="checkbox" name="confirm" value="yes">Je comprends que l’augmentation de l’autorité modifie ce que l’application Pipedrive dans ChatGPT peut demander avec ma connexion.</label></p><div class="actions"><button type="submit">Enregistrer les permissions</button><a href="/pipedrive">Annuler</a></div></form></section>` });
}
